### ISSUE TITLE
Prepare the GraphQL layer for the data

### ISSUE THREAD

**Issue by pgolovkin** [sora-xor/pricing-server#2]
Prepare the GraphQL layer for the data.
The subgraph api should be implemented like uniswap has.
The links:

1. https://uniswap.org/docs/v2/API/overview/
2. https://github.com/Uniswap/uniswap-v3-subgraph
3. https://thegraph.com/docs/introduction

**Comment by yuriiz** [comment]
https://thegraph.com is available only for Ethereum-based applications:

https://thegraph.com/docs/quick-start#faq

"19. What networks are supported by The Graph?

The graph-node supports any Ethereum-compatible JSON RPC API chain. In the Hosted service, the following networks are supported:
..."
